# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 91e88bcde231ae562c448c79e154c44312b165913d98c0e1ae1e2685f090969f7b14651c58011025f644a6947fbbaedbe1d1a9294b29f7c4070d796806d5f6fb

test:
  secret_key_base: 207e04cec238147098822b85561330028616e55bbfd25298e8b0aba8ef5757cfb318bfe1796cd228babcb4bfc1cc4e57cb56955be6a3edd7a9308a9bc65b40f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
